<a href="https://colab.research.google.com/github/onyekaokonji/AIBC/blob/main/AiBC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from keras.models import Input
from keras.layers import Dropout
from tensorflow.keras.optimizers import *

In [ ]:
# Import the dataset
train_data = pd.read_csv('/content/Train.csv')
test_data = pd.read_csv('/content/Test.csv')

## exploratory data analysis

In [ ]:
train_data.head(11)

             ID  Year_of_Birth  ... Any_Complain Response
0   ID_4A9AR6FQ           1955  ...            0        0
1   ID_X28T3VEK           1958  ...            0        0
2   ID_AWXARH57           1962  ...            0        1
3   ID_FQVZHE81           1979  ...            0        0
4   ID_QVLWGPRN           1959  ...            0        0
5   ID_3S3HRGH6           1960  ...            0        0
6   ID_KJQ9B2LE           1953  ...            0        0
7   ID_6O0NBZXD           1974  ...            0        0
8   ID_M3QFT8WO           1966  ...            0        0
9   ID_745JV5PY           1975  ...            0        0
10  ID_PTC313AB           1974  ...            0        0

[11 rows x 27 columns]

In [ ]:
train_data['Response'].value_counts()

0    1329
1     239
Name: Response, dtype: int64

In [ ]:
Response_0, Response_1 = train_data['Response'].value_counts()

In [ ]:
train_data_0 = train_data[train_data['Response'] == 0]
train_data_1 = train_data[train_data['Response'] == 1]

In [ ]:
train_data_1_over = train_data_1.sample(Response_0, replace = True)
new_train_data = pd.concat([train_data_0, train_data_1_over], axis = 0)

In [ ]:
new_train_data['Response'].value_counts()

1    1329
0    1329
Name: Response, dtype: int64

In [ ]:
print(new_train_data['Education_Level'].unique())
print(new_train_data['Marital_Status'].unique())

['Graduation' '2n Cycle' 'Master' 'PhD' 'Basic']
['Divorced' 'Together' 'Single' 'Married' 'Widow' 'Alone' 'YOLO' 'Absurd']

In [ ]:
print(test_data['Education_Level'].unique())
print(test_data['Marital_Status'].unique())

['Graduation' 'Basic' 'Master' '2n Cycle' 'PhD']
['Single' 'Widow' 'Married' 'Together' 'Divorced' 'Absurd']

In [ ]:
# We drop Marital Status because it isn't equal across datasets and Customer Date isn't relevant to accuracy
new_train_data.drop(['Marital_Status', 'Date_Customer'], axis = 1, inplace= True)

In [ ]:
test_data.drop(['Marital_Status', 'Date_Customer'], axis = 1, inplace=True)

In [ ]:
# Check for missing values in training data
new_train_data.isnull().sum()

ID                          0
Year_of_Birth               0
Education_Level             0
Disposable_Income          19
No_of_Kids_in_home          0
No_of_Teen_in_home          0
Recency                     0
Discounted_Purchases        0
WebPurchases                0
CatalogPurchases            0
StorePurchases              0
Amount_on_Wines             0
Amount_on_Fruits            0
Amount_on_MeatProducts      0
Amount_on_FishProducts      0
Amount_on_SweetProducts     0
Amount_on_GoldProds         0
WebVisitsMonth              0
Cmp3Accepted                0
Cmp4Accepted                0
Cmp5Accepted                0
Cmp1Accepted                0
Cmp2Accepted                0
Any_Complain                0
Response                    0
dtype: int64

In [ ]:
# Check for missing values in test data
test_data.isnull().sum()

ID                         0
Year_of_Birth              0
Education_Level            0
Disposable_Income          8
No_of_Kids_in_home         0
No_of_Teen_in_home         0
Recency                    0
Discounted_Purchases       0
WebPurchases               0
CatalogPurchases           0
StorePurchases             0
Amount_on_Wines            0
Amount_on_Fruits           0
Amount_on_MeatProducts     0
Amount_on_FishProducts     0
Amount_on_SweetProducts    0
Amount_on_GoldProds        0
WebVisitsMonth             0
Cmp3Accepted               0
Cmp4Accepted               0
Cmp5Accepted               0
Cmp1Accepted               0
Cmp2Accepted               0
Any_Complain               0
dtype: int64

In [ ]:
# Handling missing data

new_train_data.fillna(method='ffill', inplace=True)
test_data.fillna(method='ffill', inplace=True)

In [ ]:
new_train_data.isnull().sum()

ID                         0
Year_of_Birth              0
Education_Level            0
Disposable_Income          0
No_of_Kids_in_home         0
No_of_Teen_in_home         0
Recency                    0
Discounted_Purchases       0
WebPurchases               0
CatalogPurchases           0
StorePurchases             0
Amount_on_Wines            0
Amount_on_Fruits           0
Amount_on_MeatProducts     0
Amount_on_FishProducts     0
Amount_on_SweetProducts    0
Amount_on_GoldProds        0
WebVisitsMonth             0
Cmp3Accepted               0
Cmp4Accepted               0
Cmp5Accepted               0
Cmp1Accepted               0
Cmp2Accepted               0
Any_Complain               0
Response                   0
dtype: int64

In [ ]:
# Encoding categorical data
labelencoder = LabelEncoder()
new_train_data['Education_Level'] = labelencoder.fit_transform(new_train_data['Education_Level'])

In [ ]:
new_train_data.head(11)

             ID  Year_of_Birth  ...  Any_Complain  Response
0   ID_4A9AR6FQ           1955  ...             0         0
1   ID_X28T3VEK           1958  ...             0         0
3   ID_FQVZHE81           1979  ...             0         0
4   ID_QVLWGPRN           1959  ...             0         0
5   ID_3S3HRGH6           1960  ...             0         0
6   ID_KJQ9B2LE           1953  ...             0         0
7   ID_6O0NBZXD           1974  ...             0         0
8   ID_M3QFT8WO           1966  ...             0         0
9   ID_745JV5PY           1975  ...             0         0
10  ID_PTC313AB           1974  ...             0         0
11  ID_8QLN8M49           1989  ...             0         0

[11 rows x 25 columns]

In [ ]:
new_train_data['Response'].value_counts()

1    1329
0    1329
Name: Response, dtype: int64

In [ ]:
new_train_data.shape

(2658, 25)

In [ ]:
test_data['Education_Level'] = labelencoder.fit_transform(test_data['Education_Level'])

In [ ]:
test_data

              ID  Year_of_Birth  ...  Cmp2Accepted  Any_Complain
0    ID_ZPMABNVX           1954  ...             0             0
1    ID_WFE91NAA           1961  ...             0             0
2    ID_JV11RBRK           1973  ...             0             0
3    ID_6B7SVKY9           1970  ...             0             0
4    ID_GOVUZ545           1959  ...             0             0
..           ...            ...  ...           ...           ...
667  ID_1D68PV28           1975  ...             0             0
668  ID_TM6CYFZO           1955  ...             0             0
669  ID_VHR666SC           1952  ...             0             0
670  ID_O852YAO1           1960  ...             0             1
671  ID_ML5HMWHI           1961  ...             0             0

[672 rows x 24 columns]

In [ ]:
#  Extracting features and target data
train_data_x = new_train_data.iloc[:, 0:24]
train_data_y = new_train_data.iloc[:, 24]

In [ ]:
# Scaling the features to a range
s_scaler = StandardScaler()
train_data_x.iloc[:, 1:24] = s_scaler.fit_transform(train_data_x.iloc[:, 1:24])
test_data.iloc[:, 1:24] = s_scaler.fit_transform(test_data.iloc[:, 1:24])

In [ ]:
# Splitting train data to obtain validation_data
x_train, x_val, y_train, y_val = train_test_split(train_data_x.iloc[:, 1:24], train_data_y, test_size= 0.2, shuffle=True)

In [ ]:
x_train = np.asarray(x_train).astype('int')
x_val = np.asarray(x_val).astype('int')
y_train = np.asarray(y_train).astype('int')
y_val = np.asarray(y_val).astype('int')

# model architecture and training

In [ ]:
sapa = Sequential()
sapa.add(Input(shape=(23,)))
sapa.add(Dense(units=32, activation='relu', kernel_initializer='RandomUniform'))
sapa.add(Dense(units= 18, activation='relu', kernel_initializer='RandomUniform'))
sapa.add(Dropout(0.2))
sapa.add(Dense(units= 18, activation='relu', kernel_initializer='RandomUniform'))
sapa.add(Dense(units= 14, activation='relu', kernel_initializer='RandomUniform'))
sapa.add(Dropout(0.1))
sapa.add(Dense(units= 14, activation='relu', kernel_initializer='RandomUniform'))
sapa.add(Dense(units= 10, activation='relu', kernel_initializer='RandomUniform'))
sapa.add(Dense(units= 1, activation='sigmoid'))

In [ ]:
optim = Adam(learning_rate=0.0001, beta_1=1.2, )
sapa.compile(optimizer=optim, loss='binary_crossentropy', metrics=['Accuracy'])
check = sapa.fit(x = x_train, y = y_train, batch_size=8, epochs=200, validation_data=(x_val, y_val))

Epoch 1/200
266/266 [==============================] - 1s 3ms/step - loss: 0.1219 - Accuracy: 0.9539 - val_loss: 0.3252 - val_Accuracy: 0.9117
Epoch 2/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1141 - Accuracy: 0.9558 - val_loss: 0.3365 - val_Accuracy: 0.9117
Epoch 3/200
266/266 [==============================] - 1s 3ms/step - loss: 0.1169 - Accuracy: 0.9506 - val_loss: 0.3552 - val_Accuracy: 0.9004
Epoch 4/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1231 - Accuracy: 0.9516 - val_loss: 0.2976 - val_Accuracy: 0.9117
Epoch 5/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1195 - Accuracy: 0.9516 - val_loss: 0.3157 - val_Accuracy: 0.9211
Epoch 6/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1077 - Accuracy: 0.9563 - val_loss: 0.3605 - val_Accuracy: 0.9192
Epoch 7/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1264 - Accuracy: 0.9478 - val_loss: 0.3396 - val_Accuracy: 0.9117
Epoch 8/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1243 - Accuracy: 0.9511 - val_loss: 0.2871 - val_Accuracy: 0.9135
Epoch 9/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1118 - Accuracy: 0.9558 - val_loss: 0.3244 - val_Accuracy: 0.9135
Epoch 10/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1048 - Accuracy: 0.9567 - val_loss: 0.3048 - val_Accuracy: 0.9229
Epoch 11/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1053 - Accuracy: 0.9586 - val_loss: 0.3198 - val_Accuracy: 0.9098
Epoch 12/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1182 - Accuracy: 0.9497 - val_loss: 0.3244 - val_Accuracy: 0.9079
Epoch 13/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1120 - Accuracy: 0.9558 - val_loss: 0.3449 - val_Accuracy: 0.9173
Epoch 14/200
266/266 [==============================] - 1s 3ms/step - loss: 0.1038 - Accuracy: 0.9548 - val_loss: 0.3285 - val_Accuracy: 0.9135
Epoch 15/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0978 - Accuracy: 0.9563 - val_loss: 0.3601 - val_Accuracy: 0.9173
Epoch 16/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0961 - Accuracy: 0.9586 - val_loss: 0.3143 - val_Accuracy: 0.9229
Epoch 17/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0953 - Accuracy: 0.9586 - val_loss: 0.3576 - val_Accuracy: 0.9192
Epoch 18/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1057 - Accuracy: 0.9520 - val_loss: 0.3641 - val_Accuracy: 0.9060
Epoch 19/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1120 - Accuracy: 0.9563 - val_loss: 0.3587 - val_Accuracy: 0.9173
Epoch 20/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1101 - Accuracy: 0.9506 - val_loss: 0.3511 - val_Accuracy: 0.9248
Epoch 21/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1104 - Accuracy: 0.9530 - val_loss: 0.3556 - val_Accuracy: 0.9211
Epoch 22/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0947 - Accuracy: 0.9567 - val_loss: 0.3645 - val_Accuracy: 0.9267
Epoch 23/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0949 - Accuracy: 0.9628 - val_loss: 0.3715 - val_Accuracy: 0.9192
Epoch 24/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0939 - Accuracy: 0.9591 - val_loss: 0.4147 - val_Accuracy: 0.9192
Epoch 25/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0998 - Accuracy: 0.9638 - val_loss: 0.4150 - val_Accuracy: 0.9135
Epoch 26/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0951 - Accuracy: 0.9586 - val_loss: 0.3409 - val_Accuracy: 0.9286
Epoch 27/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0977 - Accuracy: 0.9567 - val_loss: 0.3989 - val_Accuracy: 0.9192
Epoch 28/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1009 - Accuracy: 0.9553 - val_loss: 0.3902 - val_Accuracy: 0.9173
Epoch 29/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0915 - Accuracy: 0.9633 - val_loss: 0.4134 - val_Accuracy: 0.9229
Epoch 30/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0869 - Accuracy: 0.9624 - val_loss: 0.3782 - val_Accuracy: 0.9211
Epoch 31/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0848 - Accuracy: 0.9647 - val_loss: 0.4285 - val_Accuracy: 0.9267
Epoch 32/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0938 - Accuracy: 0.9628 - val_loss: 0.3603 - val_Accuracy: 0.9286
Epoch 33/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1032 - Accuracy: 0.9586 - val_loss: 0.4710 - val_Accuracy: 0.9079
Epoch 34/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0930 - Accuracy: 0.9643 - val_loss: 0.4730 - val_Accuracy: 0.9098
Epoch 35/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0999 - Accuracy: 0.9595 - val_loss: 0.4186 - val_Accuracy: 0.9098
Epoch 36/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1155 - Accuracy: 0.9520 - val_loss: 0.3955 - val_Accuracy: 0.9154
Epoch 37/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0927 - Accuracy: 0.9638 - val_loss: 0.3705 - val_Accuracy: 0.9286
Epoch 38/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0847 - Accuracy: 0.9638 - val_loss: 0.4361 - val_Accuracy: 0.9211
Epoch 39/200
266/266 [==============================] - 1s 3ms/step - loss: 0.1083 - Accuracy: 0.9492 - val_loss: 0.3925 - val_Accuracy: 0.9229
Epoch 40/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0892 - Accuracy: 0.9600 - val_loss: 0.4453 - val_Accuracy: 0.9229
Epoch 41/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1020 - Accuracy: 0.9567 - val_loss: 0.4082 - val_Accuracy: 0.9173
Epoch 42/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0979 - Accuracy: 0.9614 - val_loss: 0.4358 - val_Accuracy: 0.9192
Epoch 43/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0982 - Accuracy: 0.9591 - val_loss: 0.4310 - val_Accuracy: 0.9192
Epoch 44/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0835 - Accuracy: 0.9638 - val_loss: 0.4756 - val_Accuracy: 0.9154
Epoch 45/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0863 - Accuracy: 0.9643 - val_loss: 0.5490 - val_Accuracy: 0.9135
Epoch 46/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0957 - Accuracy: 0.9577 - val_loss: 0.4724 - val_Accuracy: 0.9154
Epoch 47/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0855 - Accuracy: 0.9605 - val_loss: 0.4861 - val_Accuracy: 0.9098
Epoch 48/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0920 - Accuracy: 0.9591 - val_loss: 0.4805 - val_Accuracy: 0.9154
Epoch 49/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0912 - Accuracy: 0.9586 - val_loss: 0.4678 - val_Accuracy: 0.9154
Epoch 50/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0848 - Accuracy: 0.9610 - val_loss: 0.4803 - val_Accuracy: 0.9229
Epoch 51/200
266/266 [==============================] - 1s 3ms/step - loss: 0.1193 - Accuracy: 0.9511 - val_loss: 0.4767 - val_Accuracy: 0.9173
Epoch 52/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0869 - Accuracy: 0.9619 - val_loss: 0.5611 - val_Accuracy: 0.9135
Epoch 53/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0928 - Accuracy: 0.9595 - val_loss: 0.5006 - val_Accuracy: 0.9173
Epoch 54/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1023 - Accuracy: 0.9577 - val_loss: 0.4963 - val_Accuracy: 0.9173
Epoch 55/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0925 - Accuracy: 0.9600 - val_loss: 0.6101 - val_Accuracy: 0.8966
Epoch 56/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0851 - Accuracy: 0.9633 - val_loss: 0.5054 - val_Accuracy: 0.9173
Epoch 57/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0961 - Accuracy: 0.9595 - val_loss: 0.4673 - val_Accuracy: 0.9192
Epoch 58/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0819 - Accuracy: 0.9628 - val_loss: 0.4952 - val_Accuracy: 0.9117
Epoch 59/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0842 - Accuracy: 0.9633 - val_loss: 0.4950 - val_Accuracy: 0.9117
Epoch 60/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0910 - Accuracy: 0.9600 - val_loss: 0.4421 - val_Accuracy: 0.9173
Epoch 61/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0782 - Accuracy: 0.9643 - val_loss: 0.6482 - val_Accuracy: 0.9117
Epoch 62/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0849 - Accuracy: 0.9600 - val_loss: 0.6008 - val_Accuracy: 0.9135
Epoch 63/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0920 - Accuracy: 0.9610 - val_loss: 0.4752 - val_Accuracy: 0.9192
Epoch 64/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0819 - Accuracy: 0.9647 - val_loss: 0.5605 - val_Accuracy: 0.9154
Epoch 65/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0781 - Accuracy: 0.9652 - val_loss: 0.5595 - val_Accuracy: 0.9229
Epoch 66/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0756 - Accuracy: 0.9675 - val_loss: 0.6462 - val_Accuracy: 0.9117
Epoch 67/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0937 - Accuracy: 0.9605 - val_loss: 0.5055 - val_Accuracy: 0.9229
Epoch 68/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0957 - Accuracy: 0.9605 - val_loss: 0.4793 - val_Accuracy: 0.9192
Epoch 69/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0832 - Accuracy: 0.9657 - val_loss: 0.5650 - val_Accuracy: 0.9211
Epoch 70/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0787 - Accuracy: 0.9657 - val_loss: 0.6081 - val_Accuracy: 0.9173
Epoch 71/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0892 - Accuracy: 0.9591 - val_loss: 0.5820 - val_Accuracy: 0.9135
Epoch 72/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0807 - Accuracy: 0.9633 - val_loss: 0.6718 - val_Accuracy: 0.9211
Epoch 73/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0817 - Accuracy: 0.9628 - val_loss: 0.6865 - val_Accuracy: 0.9211
Epoch 74/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0780 - Accuracy: 0.9652 - val_loss: 0.5562 - val_Accuracy: 0.9229
Epoch 75/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0867 - Accuracy: 0.9619 - val_loss: 0.6063 - val_Accuracy: 0.9192
Epoch 76/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0752 - Accuracy: 0.9657 - val_loss: 0.6250 - val_Accuracy: 0.9192
Epoch 77/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1096 - Accuracy: 0.9553 - val_loss: 0.6768 - val_Accuracy: 0.9135
Epoch 78/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1004 - Accuracy: 0.9581 - val_loss: 0.5947 - val_Accuracy: 0.9154
Epoch 79/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0796 - Accuracy: 0.9647 - val_loss: 0.7008 - val_Accuracy: 0.9135
Epoch 80/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0775 - Accuracy: 0.9638 - val_loss: 0.6227 - val_Accuracy: 0.9192
Epoch 81/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0763 - Accuracy: 0.9666 - val_loss: 0.6504 - val_Accuracy: 0.9154
Epoch 82/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0728 - Accuracy: 0.9675 - val_loss: 0.8057 - val_Accuracy: 0.9211
Epoch 83/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0718 - Accuracy: 0.9666 - val_loss: 0.7442 - val_Accuracy: 0.9211
Epoch 84/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0779 - Accuracy: 0.9675 - val_loss: 0.7210 - val_Accuracy: 0.9229
Epoch 85/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0902 - Accuracy: 0.9614 - val_loss: 0.8292 - val_Accuracy: 0.9135
Epoch 86/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0907 - Accuracy: 0.9600 - val_loss: 0.6844 - val_Accuracy: 0.9267
Epoch 87/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1022 - Accuracy: 0.9577 - val_loss: 0.7658 - val_Accuracy: 0.9079
Epoch 88/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0791 - Accuracy: 0.9675 - val_loss: 0.7715 - val_Accuracy: 0.9098
Epoch 89/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0812 - Accuracy: 0.9647 - val_loss: 0.7052 - val_Accuracy: 0.9154
Epoch 90/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0825 - Accuracy: 0.9610 - val_loss: 0.6617 - val_Accuracy: 0.9248
Epoch 91/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0826 - Accuracy: 0.9633 - val_loss: 0.7884 - val_Accuracy: 0.9060
Epoch 92/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0791 - Accuracy: 0.9643 - val_loss: 0.7322 - val_Accuracy: 0.9192
Epoch 93/200
266/266 [==============================] - 1s 2ms/step - loss: 0.1036 - Accuracy: 0.9600 - val_loss: 0.7425 - val_Accuracy: 0.9117
Epoch 94/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0788 - Accuracy: 0.9633 - val_loss: 0.7060 - val_Accuracy: 0.9267
Epoch 95/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0733 - Accuracy: 0.9680 - val_loss: 0.7514 - val_Accuracy: 0.9267
Epoch 96/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0689 - Accuracy: 0.9699 - val_loss: 0.8503 - val_Accuracy: 0.9192
Epoch 97/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0794 - Accuracy: 0.9666 - val_loss: 0.7410 - val_Accuracy: 0.9173
Epoch 98/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0718 - Accuracy: 0.9699 - val_loss: 0.7284 - val_Accuracy: 0.9211
Epoch 99/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0735 - Accuracy: 0.9671 - val_loss: 0.7438 - val_Accuracy: 0.9173
Epoch 100/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0793 - Accuracy: 0.9657 - val_loss: 0.7513 - val_Accuracy: 0.9229
Epoch 101/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0772 - Accuracy: 0.9666 - val_loss: 0.5553 - val_Accuracy: 0.9380
Epoch 102/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0785 - Accuracy: 0.9680 - val_loss: 0.7725 - val_Accuracy: 0.9173
Epoch 103/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0803 - Accuracy: 0.9657 - val_loss: 0.7388 - val_Accuracy: 0.9173
Epoch 104/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0792 - Accuracy: 0.9652 - val_loss: 0.7550 - val_Accuracy: 0.9173
Epoch 105/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0738 - Accuracy: 0.9671 - val_loss: 0.8994 - val_Accuracy: 0.9135
Epoch 106/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0884 - Accuracy: 0.9600 - val_loss: 0.4901 - val_Accuracy: 0.9211
Epoch 107/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0871 - Accuracy: 0.9614 - val_loss: 0.6304 - val_Accuracy: 0.9173
Epoch 108/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0839 - Accuracy: 0.9638 - val_loss: 0.7645 - val_Accuracy: 0.9117
Epoch 109/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0798 - Accuracy: 0.9647 - val_loss: 0.6515 - val_Accuracy: 0.9192
Epoch 110/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0763 - Accuracy: 0.9675 - val_loss: 0.7592 - val_Accuracy: 0.9211
Epoch 111/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0748 - Accuracy: 0.9666 - val_loss: 0.8142 - val_Accuracy: 0.9248
Epoch 112/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0783 - Accuracy: 0.9675 - val_loss: 0.8488 - val_Accuracy: 0.9173
Epoch 113/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0915 - Accuracy: 0.9610 - val_loss: 0.8555 - val_Accuracy: 0.9098
Epoch 114/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0797 - Accuracy: 0.9661 - val_loss: 0.8769 - val_Accuracy: 0.9117
Epoch 115/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0723 - Accuracy: 0.9713 - val_loss: 0.8020 - val_Accuracy: 0.9192
Epoch 116/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0761 - Accuracy: 0.9666 - val_loss: 0.8348 - val_Accuracy: 0.9173
Epoch 117/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0749 - Accuracy: 0.9675 - val_loss: 0.8900 - val_Accuracy: 0.9135
Epoch 118/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0759 - Accuracy: 0.9666 - val_loss: 0.8413 - val_Accuracy: 0.9117
Epoch 119/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0799 - Accuracy: 0.9633 - val_loss: 0.9105 - val_Accuracy: 0.9098
Epoch 120/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0824 - Accuracy: 0.9675 - val_loss: 0.8383 - val_Accuracy: 0.9229
Epoch 121/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0749 - Accuracy: 0.9671 - val_loss: 0.9150 - val_Accuracy: 0.9192
Epoch 122/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0711 - Accuracy: 0.9657 - val_loss: 0.8104 - val_Accuracy: 0.9173
Epoch 123/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0802 - Accuracy: 0.9657 - val_loss: 0.6531 - val_Accuracy: 0.9154
Epoch 124/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0773 - Accuracy: 0.9675 - val_loss: 0.8081 - val_Accuracy: 0.9192
Epoch 125/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0713 - Accuracy: 0.9661 - val_loss: 1.1392 - val_Accuracy: 0.9192
Epoch 126/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0818 - Accuracy: 0.9619 - val_loss: 0.8853 - val_Accuracy: 0.9117
Epoch 127/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0730 - Accuracy: 0.9671 - val_loss: 0.8978 - val_Accuracy: 0.9192
Epoch 128/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0669 - Accuracy: 0.9690 - val_loss: 0.9371 - val_Accuracy: 0.9229
Epoch 129/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0884 - Accuracy: 0.9605 - val_loss: 0.8199 - val_Accuracy: 0.9135
Epoch 130/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0926 - Accuracy: 0.9600 - val_loss: 0.6729 - val_Accuracy: 0.9192
Epoch 131/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0803 - Accuracy: 0.9652 - val_loss: 0.8564 - val_Accuracy: 0.9248
Epoch 132/200
266/266 [==============================] - 1s 3ms/step - loss: 0.0849 - Accuracy: 0.9661 - val_loss: 0.6442 - val_Accuracy: 0.9248
Epoch 133/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0726 - Accuracy: 0.9699 - val_loss: 0.6916 - val_Accuracy: 0.9248
Epoch 134/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0782 - Accuracy: 0.9633 - val_loss: 0.8325 - val_Accuracy: 0.9173
Epoch 135/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0870 - Accuracy: 0.9643 - val_loss: 0.6339 - val_Accuracy: 0.9060
Epoch 136/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0760 - Accuracy: 0.9685 - val_loss: 0.8147 - val_Accuracy: 0.9060
Epoch 137/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0734 - Accuracy: 0.9675 - val_loss: 0.7835 - val_Accuracy: 0.9135
Epoch 138/200
266/266 [==============================] - 1s 2ms/step - loss: 0.0744 - Accuracy: 0.9657 - val_loss: 0.7728 - val_Accuracy: 0.9060
Epoch 139/200

In [ ]:
pred = sapa.predict(test_data.iloc[:, 1:24])

In [ ]:
pred = np.rint(pred)

In [ ]:
pred = pred.reshape(-1)

# generating submission file

In [ ]:
submission = pd.DataFrame({'ID': test_data['ID'], 'Response': pred})
submission.head(6)

            ID  Response
0  ID_ZPMABNVX       0.0
1  ID_WFE91NAA       0.0
2  ID_JV11RBRK       0.0
3  ID_6B7SVKY9       1.0
4  ID_GOVUZ545       0.0
5  ID_A3SFW973       0.0

In [ ]:
Filename = 'Submission.csv'

submission.to_csv(Filename, index=False)